import { prisma } from '../prisma';
import { ProofEngine } from '@race/proof-engine';
import { AuditEventDto } from '@race/types';

export interface RecordAuditEventInput {
  eventType: string;

  actorType:
  | 'BUYER'
  | 'BUYER_AGENT'
  | 'MERCHANT'
  | 'GROWTH_AGENT'
  | 'POLICY_ENGINE'
  | 'RISK_ENGINE'
  | 'RAZORPAY_GATEWAY'
  | 'SYSTEM';

  actorId: string;

  resourceType:
  | 'MANDATE'
  | 'PRODUCT'
  | 'ORDER'
  | 'PAYMENT'
  | 'PROOF'
  | 'CAMPAIGN'
  | 'PLATFORM';

  resourceId: string;

  decision?:
  | 'ALLOW'
  | 'BLOCK'
  | 'REQUIRE_CONFIRMATION'
  | 'SUCCESS'
  | 'FAILURE'
  | 'CREATED';

  reasonCodes?: string[];

  metadata?: Record<string, unknown>;
}

export class AuditService {
  private static writeQueue: Promise<unknown> = Promise.resolve();

  /**
   * Records an audit event chained cryptographically
   * to the previous audit event.
   *
   * Enqueues writes sequentially to guarantee strict linear
   * previousHash chaining under concurrent API requests.
   */
  public static async recordEvent(
    input: RecordAuditEventInput
  ): Promise<AuditEventDto> {
    const next = AuditService.writeQueue.then(() =>
      AuditService.internalRecordEvent(input)
    );
    AuditService.writeQueue = next.catch(() => {});
    return next;
  }

  private static async internalRecordEvent(
    input: RecordAuditEventInput
  ): Promise<AuditEventDto> {
    // ---------------------------------------------------------
    // 1. Get the latest audit event
    // ---------------------------------------------------------
    const latestEvent = await prisma.auditEvent.findFirst({
      orderBy: [
        {
          createdAt: 'desc'
        },
        {
          id: 'desc'
        }
      ]
    });

    const previousHash = latestEvent
      ? latestEvent.hash
      : '0'.repeat(64);

    // ---------------------------------------------------------
    // 2. Normalize values
    // ---------------------------------------------------------
    const reasonCodes = input.reasonCodes ?? [];
    const metadata = input.metadata ? JSON.parse(JSON.stringify(input.metadata)) : {};

    /*
     * IMPORTANT:
     *
     * We intentionally do NOT include a separately generated
     * timestamp in the hash.
     *
     * The AuditEvent database row has createdAt generated by
     * Prisma. Including another timestamp here would mean the
     * verifier would not have the exact same value available.
     *
     * The hash therefore consists of the immutable audit fields
     * below.
     */
    const hashPayload = {
      eventType: input.eventType,
      actorType: input.actorType,
      actorId: input.actorId,
      resourceType: input.resourceType,
      resourceId: input.resourceId,
      decision: input.decision ?? null,
      reasonCodes,
      metadata,
      previousHash
    };

    // ---------------------------------------------------------
    // 3. Generate SHA-256 hash
    // ---------------------------------------------------------
    const hash = ProofEngine.computeEventHash(hashPayload);

    // ---------------------------------------------------------
    // 4. Persist the event
    // ---------------------------------------------------------
    const created = await prisma.auditEvent.create({
      data: {
        eventType: input.eventType,
        actorType: input.actorType,
        actorId: input.actorId,
        resourceType: input.resourceType,
        resourceId: input.resourceId,

        decision: input.decision ?? null,

        reasonCodes: JSON.stringify(reasonCodes),

        metadata: JSON.stringify(metadata),

        previousHash,

        hash
      }
    });

    // ---------------------------------------------------------
    // 5. Return DTO
    // ---------------------------------------------------------
    return {
      id: created.id,
      eventType: created.eventType,
      actorType: created.actorType,
      actorId: created.actorId,
      resourceType: created.resourceType,
      resourceId: created.resourceId,
      decision: created.decision,

      reasonCodes: created.reasonCodes
        ? JSON.parse(created.reasonCodes)
        : [],

      metadata: created.metadata
        ? JSON.parse(created.metadata)
        : {},

      previousHash: created.previousHash,

      hash: created.hash,

      createdAt: created.createdAt.toISOString()
    };
  }

  /**
   * Retrieves the audit chain in chronological order.
   */
  public static async getChain(
    limit: number = 100
  ): Promise<AuditEventDto[]> {
    const events = await prisma.auditEvent.findMany({
      orderBy: [
        {
          createdAt: 'asc'
        },
        {
          id: 'asc'
        }
      ],
      take: limit
    });

    return events.map((event) => ({
      id: event.id,

      eventType: event.eventType,

      actorType: event.actorType,

      actorId: event.actorId,

      resourceType: event.resourceType,

      resourceId: event.resourceId,

      decision: event.decision,

      reasonCodes: event.reasonCodes
        ? JSON.parse(event.reasonCodes)
        : [],

      metadata: event.metadata
        ? JSON.parse(event.metadata)
        : {},

      previousHash: event.previousHash,

      hash: event.hash,

      createdAt: event.createdAt.toISOString()
    }));
  }
}